# Generated by Django 2.0.5 on 2018-06-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='file_type',
            field=models.CharField(max_length=1400000000000000000),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_title',
            field=models.CharField(max_length=1400000000000000000),
        ),
    ]
