# Generated by Django 2.0.5 on 2018-06-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
