# Generated by Django 2.0.5 on 2018-06-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_plantrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrip',
            name='placename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
