# Generated by Django 2.0.5 on 2018-06-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20180623_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantrip',
            name='priority',
        ),
    ]
