# Generated by Django 2.0.5 on 2018-06-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_plantrip_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='file_type',
            new_name='place_type',
        ),
    ]
