# Generated by Django 2.0.5 on 2018-06-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20180623_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='cityname',
        ),
    ]
