# Generated by Django 2.0.5 on 2018-06-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20180623_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='cityname',
            new_name='city',
        ),
    ]
