# Generated by Django 2.0.5 on 2018-06-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20180623_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='body',
            new_name='state',
        ),
    ]
