# Generated by Django 2.0.5 on 2018-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_application_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_manager',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
