# Generated by Django 2.0.5 on 2018-06-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20180627_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application_manager',
        ),
    ]
