# Generated by Django 2.0.5 on 2018-06-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_delete_application_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_favorite',
        ),
    ]
