# Generated by Django 2.0.5 on 2018-06-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_remove_place_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='body',
            new_name='description',
        ),
    ]
